name = "s-dftd3"
version = "0.4.1"
license = "LGPL-3.0-or-later"
maintainer = ["@awvwgk"]
author = ["Sebastian Ehlert"]
copyright = "2019-2021 Sebastian Ehlert"
description = "Simple reimplementation of the DFT-D3 method"
keywords = ["dispersion-correction", "quantum-chemistry"]

[dependencies]
[dependencies.mctc-lib]
git = "https://github.com/grimme-lab/mctc-lib"
tag = "v0.2.3"

[dev-dependencies]
[dev-dependencies.mstore]
git = "https://github.com/grimme-lab/mstore"
tag = "v0.1.2"

[build]
auto-tests = false

[[test]]
name = "tester"
source-dir = "test/unit"
